spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
bitpay:
  uri: https://bitpay.com/api/rates